version: '2'
services:
  spingular-app:
    image: spingular
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spingular-postgresql:5432/spingular
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  spingular-postgresql:
    extends:
      file: postgresql.yml
      service: spingular-postgresql
